### ISSUE TITLE
function should return and not just print out

### ISSUE THREAD

**Issue by ChuckNorrison** [meshtastic/Meshtastic-python#102]
https://github.com/meshtastic/Meshtastic-python/blob/037d29e2007efae971d3c05ca721d11f3b6d9976/meshtastic/__init__.py#L230

usage example
```
info = meshtastic_interface.showInfo()
nodes = meshtastic_interface.showNodes()
```

It would be great to return the table to print the information within another python program which calls the function.

**Comment by jdstroy** [comment]
That information should already be present in the API:

```
import meshtastic
ti = meshtastic.TCPInterface("Meshtastic-0123.lan");
ti.nodes["nodeId"]['position'] # is this what you're looking for?
```

**Comment by ChuckNorrison** [comment]
i solved it for me this way, its not beautiful but works

**Comment by mkinney** [comment]
Can we close this issue?

**Comment by ChuckNorrison** [comment]
Works for me :+1:
