### ISSUE TITLE
add --setbluetoothpin

### ISSUE THREAD

**Issue by nconder** [meshtastic/Meshtastic-python#11]
Add --setbluetoothpin for device that do not have screens. _I would see this being used as more of a one off._ 

Above enhancement similar to https://github.com/meshtastic/Meshtastic-device/issues/357 _This might be uses for bulk device provisioning for teams like [AndroidTacticalAssaultKit-CIV](https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV)_

**Comment by geeksville** [comment]
we'll probably do this in the device side by providing an alternate (less secure) paring method.  The current pairing flow is mandated by the bluetooth sig to use the code provided by the phone on the fly.
