### ISSUE TITLE
Destination node id format : ‘dict’ object has no attribute ‘num’

### ISSUE THREAD

**Issue by JL-EU** [meshtastic/Meshtastic-python#12]
When using the command line:
meshtastic --dest '!ac67b21bb0e8' --sendtext 'Hello e8'
Trigger powerFSM 9
Connected to radio
Sending text message Hello e8 to !ac67b21bb0e8
'dict' object has no attribute 'num'

See also description:
https://meshtastic.discourse.group/t/destination-node-id-format/1221?u=jl-eu

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/destination-node-id-format/1221/3
