### ISSUE TITLE
Ideal to make builds of Meshtastic-python as a GitHub action

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-python#124]
Ideal to make builds of Meshtastic-python as a GitHub action

**Comment by andrekir** [comment]
build information here: https://meshtastic.org/docs/developers/publish#python

**Comment by mkinney** [comment]
Using https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ as a guide

**Comment by mkinney** [comment]
token name used: "GitHub Actions CI — meshtastic/Meshtastic-python" (don't think it matters)

https://github.com/pypa/gh-action-pypi-publish has docs on use

**Comment by mkinney** [comment]
#195

**Comment by mkinney** [comment]
It's working! It's working!

Thanks to @sachaw and @mc-hamster
