### ISSUE TITLE
--setpref requires the property and value to be an integer

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-python#14]
If anything other than an integer is passed to setpref, an error is returned.

`"Connected to radio
Setting preference wifi_ssid to myssid
Can't set wifi_ssid due to invalid literal for int() with base 10: 'myssid'
`

Problem is here:

![image](https://user-images.githubusercontent.com/12804989/93029022-03425100-f5cd-11ea-8cd7-313022357124.png)

**Comment by geeksville** [comment]
@mc-hamster to facilitate your new hotness.  example usage here: https://github.com/meshtastic/Meshtastic-python/commit/be8c654eea7ac606ae99005000e9a481f7845f41

**Comment by mc-hamster** [comment]
Thanks. I should have some time either tonight or tomorrow.

Cheers mate!
