### ISSUE TITLE
missing comma in Meshtastic-python/setup.py

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-python#15]
Missing a comma in setup.py

Error:

![image](https://user-images.githubusercontent.com/12804989/93286607-81008b00-f78c-11ea-9034-d8e4116d26db.png)

Fix is to add a comma in setup.py

![image](https://user-images.githubusercontent.com/12804989/93286195-7f829300-f78b-11ea-874f-b21b870380fd.png)

**Comment by mc-hamster** [comment]
I added a comma to that file in my local environment and was able to install the library.

**Comment by geeksville** [comment]
thanks!  fixed!
