### ISSUE TITLE
SerialPlugin - Feature Request - NMEA 

### ISSUE THREAD

**Issue by jobionekabnoi** [meshtastic/Meshtastic-python#160]
--SerialPlugin to output discovered Nodes in mesh to w/ GPS Coordinates to NMEA string

**Comment by mkinney** [comment]
Any updates on this?

**Comment by Black6spdZ** [comment]
any reason for NMEA? it isn't the most compact protocol

**Comment by mkinney** [comment]
We are open to PRs. For now, going to close this issue. Feel free to re-open or create a new issue.
