### ISSUE TITLE
add ability to reset the node db via cli

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-python#173]
Sometimes the node db is out of date or has erroneous info, so would like a way to force a reset of the node db without doing a "factory_reset true".

**Comment by mkinney** [comment]
Perhaps add a `--clear-nodes`?

**Comment by mkinney** [comment]
See https://github.com/meshtastic/Meshtastic-device/issues/1016

**Comment by garthvh** [comment]
Complete
