### ISSUE TITLE
Request persistent config to set serialUSB port

### ISSUE THREAD

**Issue by jaykayenn** [meshtastic/Meshtastic-python#185]
Meshtastic boards appear on /dev/ttyACM for me while my /ttyUSB ports are permanently occupied by laptop modems. This requires including --port in every CLI command. 

Request a text config.ini to persistently set the desired Meshtastic port. 

Thanks

```
DEBUG:root:Not logging serial output
DEBUG:root:ports:['/dev/ttyACM0', '/dev/ttyUSB0', '/dev/ttyUSB1', '/dev/ttyUSB2']
Warning: Multiple serial ports were detected so one serial port must be specified with the '--port'.
  Ports detected:['/dev/ttyACM0', '/dev/ttyUSB0', '/dev/ttyUSB1', '/dev/ttyUSB2']
```

**Comment by mkinney** [comment]
I thought of a non-coding option.

Create a script like this:
```
meshtastic --port /dev/ttyACM0 "$@"
```

Put that script somewhere in your path, then just use that instead of using `meshtastic` directly.

**Comment by jaykayenn** [comment]
> I thought of a non-coding option.
> 
> Create a script like this:
> 
> ```
> meshtastic --port /dev/ttyACM0 "$@"
> ```
> 
> Put that script somewhere in your path, then just use that instead of using `meshtastic` directly.

That's useful, thanks!

**Comment by mkinney** [comment]
Great! Ok to close this issue?

**Comment by jaykayenn** [comment]
Workaround with local shell script.
