### ISSUE TITLE
--reply mode does not work

### ISSUE THREAD

**Issue by Beiri22** [meshtastic/Meshtastic-python#190]
When using ```meshtastic --reply``` the python app does connect to radio and then terminate. When in reply mode the app should stay alive and listen for messages until CRTL-C.

```__main__.py``` has this loop on lines 64x, but does not include the case of reply:
```
   if args.noproto or (have_tunnel and args.tunnel):  # loop until someone presses ctrlc
                while True:
                    time.sleep(1000)
```

**Comment by mkinney** [comment]
I've been trying to figure out how the `--reply` option was supposed to work. Thanks for sharing!

**Comment by mkinney** [comment]
Thanks for the info/contribution.

Code was merged.

Ok to close issue?

**Comment by mkinney** [comment]
We released a new version of meshtastic today with your code merged.

Can you see if it does what you expect?
