### ISSUE TITLE
Error if message payload contains non-unicode bytes

### ISSUE THREAD

**Issue by a-f-G-U-C** [meshtastic/Meshtastic-python#27]
https://github.com/meshtastic/Meshtastic-python/blob/0d7ef3a1096cd3bf462ec505affb631d15fe4ae6/meshtastic/__init__.py#L373-L374
This throws an exception if the message payload is raw binary (protobuf, layered encryption etc). 
EDIT: ... which I understand that it **shouldn't**, but can still happen O:-)

**Comment by geeksville** [comment]
oops - thanks - I'll fix
