### ISSUE TITLE
trying to use     meshtastic --port /dev/ttyUSB0 --seriallog stdout   as dumb terminal

### ISSUE THREAD

**Issue by bradshawlupton** [meshtastic/Meshtastic-python#286]
We are  trying to pass text messages from one ubuntu node to another in a 4 node ham meshtastic mesh  on 433 mhz 

meshtastic --port /dev/ttyUSB0 --seriallog stdout
Shutdown BT: 217020 heap size
Connected to radio

We are attempting to just dump the messages sent from one node    (any other traffic is fine too)   to a remote node  heltec-v2.0

wish to use usb on ubuntu, no androids for now.

BT is a future, wifi is a desired near future

significan yagi antennas over buzzards bay and the cape cod canal for tidal sensors for STEM is the target. 

               Thanks, Bradshaw

**Comment by mkinney** [comment]
I don't think that's what seriallog is intended to do. I think `--seriallog` is intended to just capture the serial output a file.

I think for what you are trying to do there are two options:
1) use MQTT (might be overkill)
2) setup a python program to subscribe to events (I've not done this yet, so it might take a bit of experiementation)
