### ISSUE TITLE
[Bug]: Issues setting psk key via serial

### ISSUE THREAD

**Issue by rwcts** [meshtastic/Meshtastic-python#317]
### Category

Serial

### Hardware

T-Beam, Heltec v2.1

### Firmware Version

1.2.52

### Description

This includes versions 1.2.59 and 1.2.58.

When programming a new Heltec or TBeam unit via serial using the below commands it fails. (Note COM9 has to be used as there are other internal devices that use com ports. This is done via Phython install on Windows 11 64bit.

meshtastic --ch-set psk random --ch-index 0 --port COM9
meshtastic --ch-set psk KEYHERE --info --ch-index 0 --port COM9

The only way to get the key in is to attempt to use the client.meshtastic.org site using serial and then paste the key into the gui. Using the client.meshtastic.org site sometimes takes several times to connect it but it eventually works and saves the changes. 

### Relevant log output

```Shell
C:\Users\User>
C:\Users\User>meshtastic --ch-set psk random --ch-index 0 --port COM9
Connected to radio
Writing modified channels to device

C:\Users\User>meshtastic --ch-set psk KEYHERE --info --ch-index 0 --port COM9
Connected to radio
Aborting due to: 'KEYHERE' has type str, but expected one of: bytes
```

**Comment by mkinney** [comment]
The actual string must be in the "0x<HEX><HEX>..." and it must be a specific length, depending on which level you want. (16 bytes for AES128 or 32 for AES256)

**Comment by mkinney** [comment]
Note: The string displayed when using `--info` is not the same value that would be used here.

**Comment by rwcts** [comment]
> 

I have confirmed that the key used is not the one showing in --info so that is correct. I did --ch-set psk random --ch-index 0 and then logged into the client.meshtastic.org and looked at the key it generated. The key was +ZDoJyvLSPhCBuT6IKCMiOE1l6pJc+VN19S4AGhyFi0=  

So when using the python serial interface (command prompt) and then entering in the below command, it should not work as its not HEX. If that is the case then its a "me" problem not a bug.

meshtastic --ch-set psk +ZDoJyvLSPhCBuT6IKCMiOE1l6pJc+VN19S4AGhyFi0= --info --ch-index 0 --port COM9

**Comment by mkinney** [comment]
The way the `--ch-set psk` is written, is it expects the values to be in a different format than the string representations that you have listed.

It's not really a "you" issue. It's just the way the code is currently written. To allow a string format, it would require some coding.

**Comment by sachaw** [comment]
The web UI will allow you to copy/paste keys between devices
