### ISSUE TITLE
Incorrect version 1.2.93 in last brach 1.2.40

### ISSUE THREAD

**Issue by amerinoj** [meshtastic/Meshtastic-python#320]
Hi, I think the version was not updated in last brach

./run.sh --version
1.2.93

**Comment by mkinney** [comment]
What is in the contents of "run.sh"?

**Comment by amerinoj** [comment]
Is the file 
meshtastic/Meshtastic-python/bin/run.sh

**Comment by mkinney** [comment]
What does `meshtastic --version` show?

What does `which meshtastic` show?
