### ISSUE TITLE
Documentation: What 'preferences' exist, how to change user settings?

### ISSUE THREAD

**Issue by hb9eue** [meshtastic/Meshtastic-python#34]
Hi

I have been searching the site and some of the code to figure out, what settings can be made via the example application. No success. Sorry probably more a user question than a developer question who could for sure have found the answer looking at the meshtastic-device code.

What i am looking for is how to set the longName and shortName to get more usefull names when sending messages via the meshtastic-python.

-Benoît-

**Comment by geeksville** [comment]
hi @hb9eue,

By coincidence @timgunter just added support for setting shortname/longname see the new --setowner command line option for an example.

Alas our prefs docs are currently pretty weak.  The gold standard right now is in the protobuf internal documentation:

https://github.com/meshtastic/Meshtastic-protobufs/blob/master/mesh.proto#L140

(also github is fine for this, but you might get quicker answers on our forum: [meshtastic.discourse.group](meshtastic.discourse.group) )
