### ISSUE TITLE
Meshtastic don't detect devices with 1.3.20 firmware

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/Meshtastic-python#345]
```
root@quantum:~# meshtastic --version
1.2.95
root@quantum:~# meshtastic --ch-longslow --set region EU865 --reboot
Warning: No Meshtastic devices detected.
root@quantum:~# lsusb | grep 1a86
Bus 001 Device 010: ID 1a86:55d4 QinHeng Electronics USB Single Serial
root@quantum:~# 
```

**Comment by caveman99** [comment]
Sorry, this is by design. Meshtastic 1.2.x CLI (and any other 1.2.x client) does not work with 1.3.x firmware.

**Comment by caveman99** [comment]
1.3alpha.8 was just sent on the way which will start working with 1.3.21 firmware again.

**Comment by garthvh** [comment]
The CLI for 1.3 is installed with pip install --upgrade meshtastic --pre without the pre you get 1.2
