### ISSUE TITLE
Can't disable wifi with Python 3 on Windows

### ISSUE THREAD

**Issue by scarolan** [meshtastic/Meshtastic-python#357]
The meshtastic command line example for disabling wifi doesn't accept `""` as a valid parameter

```
meshtastic --set wifi_ap_mode false --set wifi_ssid "" --set wifi_password ""
```

produces this output on Windows Powershell with Python3:

```
meshtastic: error: argument --set: expected 2 arguments
```

**Comment by garthvh** [comment]
There is a wifi.enabled Boolean in the protobufs now, it is not fully implemented

**Comment by garthvh** [comment]
The value is Saving properly to the device, there is still an open device issue

https://github.com/meshtastic/Meshtastic-device/issues/1595

**Comment by scarolan** [comment]
Thanks for the quick response.
