### ISSUE TITLE
Warning: wifi_password must be at least 8 characters

### ISSUE THREAD

**Issue by scarolan** [meshtastic/Meshtastic-python#358]
The docs suggest that you should set wifi_ssid and wifi_password to empty strings to disable wifi.

But when you attempt to do that this error pops up:

```
Warning: wifi_password must be 8 or more characters.
```

This is confusing for new users.  Maybe a separate setting to toggle whether wifi is enabled might be better.

**Comment by garthvh** [comment]
Those docs are for 1.2

https://meshtastic.org/docs/settings/config/wifi#disable-wifi

**Comment by scarolan** [comment]
Sorry.  it wasn't clear to me that those numbers on the left were versions...


![image](https://user-images.githubusercontent.com/403332/184449911-df5edb0f-9dfe-40eb-978a-d3a566781dea.png)

**Comment by scarolan** [comment]
Also, your FAQ still points at the 1.2 docs

https://meshtastic.org/docs/faq/wifi
