### ISSUE TITLE
1.3 include lora_config in channel url

### ISSUE THREAD

**Issue by andrekir** [meshtastic/Meshtastic-python#359]
- in 1.3 lora_config was added to ApponlyProtos.ChannelSet and needs to be included in [getURL](https://github.com/meshtastic/Meshtastic-python/blob/7c6e87e1619f916976d80931635ce45e198b3f1e/meshtastic/node.py#L321) and [setURL](https://github.com/meshtastic/Meshtastic-python/blob/7c6e87e1619f916976d80931635ce45e198b3f1e/meshtastic/node.py#L333) functions.

**Comment by thebentern** [comment]
Fixed in latest release
