### ISSUE TITLE
CLI Reports ModemPreset Has No Value for ch-mid command-line options

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic-python#367]
meshtastic --ch-midfast and meshtastic --ch-midslow both error with similar errors:

Connected to radio
Aborting due to: Enum ModemPreset has no value defined for name 'MidFast'

Connected to radio
Aborting due to: Enum ModemPreset has no value defined for name 'MidSlow'

All other channel presets seem to work okay.  
Using meshtastic installed via pip.  Package info: meshtastic-1.3a26-py3.8.egg

**Comment by garthvh** [comment]
/// Long Range - Fast
  case longFast // = 0
  /// Long Range - Slow
  case longSlow // = 1
 /// Very Long Range - Slow
 case vlongSlow // = 2
 /// Medium Range - Slow
 case medSlow // = 3
 /// Medium Range - Fast
 case medFast // = 4
 /// Short Range - Slow
 case shortSlow // = 5
 /// Short Range - Fast
  case shortFast // = 6
  
  Are the modem preset values from 1.3, the mid is an old typo.

**Comment by ghostop14** [comment]
It may be from the command-line parsing:

**Comment by ghostop14** [comment]
Looks like the mismatch is in __main__.py:

        if args.ch_midslow:
            setSimpleConfig(config_pb2.Config.LoRaConfig.ModemPreset.MidSlow)

        if args.ch_midfast:
            setSimpleConfig(config_pb2.Config.LoRaConfig.ModemPreset.MidFast)

**Comment by ghostop14** [comment]
Cloned meshtastic-python and fixed and built locally. Changing those lines in __main__py to Med rather than Mid fixes the command-line issue.

**Comment by garthvh** [comment]
Please submit a pull request

**Comment by ghostop14** [comment]
Just submitted.
