### ISSUE TITLE
Releases Meshtastic CLI for MAC

### ISSUE THREAD

**Issue by Piter-NS** [meshtastic/Meshtastic-python#372]
Why the MAC version of CLI has been discontinued?

**Comment by caveman99** [comment]
It has not been discontinued. What exactly are you looking for?

**Comment by Piter-NS** [comment]
I would like to download compiled version of CLI for MAC. The latest version was Meshtastic Python 1.3alpha.16 in Releases section. Since then I can't find compiled version CLI for MAC.

**Comment by Piter-NS** [comment]
Why the MAC version of CLI has been discontinued?

**Comment by sachaw** [comment]
The VLI isnt compiled and relies you installing it via pip, please see the documentation on our website
