### ISSUE TITLE
T-Beam M8N SX1262 Issue with CLI

### ISSUE THREAD

**Issue by adrienbeaussier** [meshtastic/Meshtastic-python#373]
Hello,

I have an issue when trying to use the Python CLI with an up-to-date T-Beam with M8N & SX1262.
I am able to flash it with the latest firmware version (1.3.40), but when trying to set the region with the latest CLI version (1.3.29), it fails as the `region` parameter is not recognised.

Here is a summary of my experiments:

```
| Firmware | Meshtastic CLI | --info                            | --set region                      |
|----------|----------------|-----------------------------------|-----------------------------------|
| 1.3.40   | 1.3.29         | OK: https://pastebin.com/qKkZz4Kv | KO: https://pastebin.com/dpKcN5zy |
| 1.3.40   | 1.2.95         | KO: Exception: Timed out          | KO: Exception: Timed out          |
| 1.2.65   | 1.3.29         | KO: Exception: Timed out          | KO: Exception: Timed out          |
| 1.2.65   | 1.2.95         | OK: https://pastebin.com/8Jcs1ULe | OK                                |
```

And here is the ouput of the `meshtastic --support` command with the latest updates:
>System: Linux
   Platform: Linux-5.14.0-1051-oem-x86_64-with-glibc2.29
   Release: 5.14.0-1051-oem
   Machine: x86_64
   Encoding (stdin): utf-8
   Encoding (stdout): utf-8
 meshtastic: v1.3.29
 Executable: /home/laptop-1/.local/bin/meshtastic
 Python: 3.8.10 CPython GCC 9.4.0

**Comment by garthvh** [comment]
The syntax for 1.3 has changed https://meshtastic.org/docs/settings/config/lora
