### ISSUE TITLE
Feature Request: Ability to set long and short name in a single command

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic-python#382]
Setting either long or short name triggers a device reboot.  Would be nice to set them in one command for a single reboot.

**Comment by garthvh** [comment]
When using the CLI you can chain commands, which is what you want. the device reboots every time a user object is saved with one or more values.

meshtastic --set-owner 'fun names' --set lora.region 1

**Comment by ghostop14** [comment]
Oh, perfect. Didn't know that.  Thanks!
