### ISSUE TITLE
Can't send text with meshtastic.py --sendtext

### ISSUE THREAD

**Issue by timgunter** [meshtastic/Meshtastic-python#39]
When I run "meshtastic --sendtext some_message", onConnected() closes the interface before the message is sent. Since onConnected is called from a thread managed by pubsub, i'm not sure what the best way to resolve this is. Do we need a way to check if the message has been sent? Or to optionally block until it has been sent? Do we need to add an isBusy threading.Event to MeshInterface?

**Comment by timgunter** [comment]
Perhaps the best thing to do is just set closeNow to False

**Comment by geeksville** [comment]
ooh thanks I think this is a problem with how sent bytes are being treated when closing the serial port.  It seems like they might be getting dropped when the port is closed (even though we previously called serial.flush() to wait for them getting sent.  I think this might mean the problem you saw is a dup of #41 

@timgunter can I ask if you are using windows? (I'm having a hard time reproing this on linux)

**Comment by geeksville** [comment]
I just created a nasty possible fix (see my commit in #41) - would you mind trying it on your machine?

**Comment by geeksville** [comment]
closing as a dup of #41
