### ISSUE TITLE
Port nums coming through as strings

### ISSUE THREAD

**Issue by timgunter** [meshtastic/Meshtastic-python#42]
Portnums are being stored as strings instead of ints in packet['decoded']['data']['portnum'].

When I register a callback with "meshtastic.receive", and send the device a text message, I get the string 'TEXT_MESSAGE_APP' and not the enum value 1. The portnums_pb2.TEXT_MESSAGE_APP is an int == 1 so comparing the value from the packet to the portnums_pb2.TEXT_MESSAGE_APP returns False.

**Comment by geeksville** [comment]
merged (mostly)
