### ISSUE TITLE
Simplified, tabular output of meshtastic –info 

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-python#54]
I was wondering whether it might be a good idea to add a switch to format the output of

`meshtastic --info`

in tabular form **and** reduce data to a minimum when just a quick glance at the mesh status is required.

Output examples:

| user | position | battery | snr |
| ---|---|---|---|
|longName|latitude, longitude, altitude|batteryLevel|snr|

| user | distance | battery | snr |
| ---|---|---|---|
|longName|distance, bearing|batteryLevel|snr|

It could be invoked with

`meshtastic --nodes`

Reference: https://meshtastic.discourse.group/t/simplified-tabular-output-of-meshtastic-info/2468

**Comment by geeksville** [comment]
fixed by @iz1kga - thanks! in https://github.com/meshtastic/Meshtastic-python/pull/56
