### ISSUE TITLE
meshtastic --help replies --set-router use --set router true instead of is_router true

### ISSUE THREAD

**Issue by nicholseric** [meshtastic/Meshtastic-python#69]
meshtastic 1.2.10 --help replies --set-router use --set router true instead of is_router true

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/1-2-16-alpha-of-device-android-and-python-lib-tool-is-out/2991/3
