### ISSUE TITLE
"meshtastic.receive.data" throws KeyError if receiving data via interface.sendData()

### ISSUE THREAD

**Issue by whi-tw** [meshtastic/Meshtastic-python#7]
Hi,

When sending data in the form `interface.sendData(b'some-bytes'), the following is thrown:
```
ERROR:root:Error handling FromRadio, possibly corrupted? 'typ'
Traceback (most recent call last):
  File "/home/tnwhitwell/workspace/scouts/meshtastic-scouts/.direnv/python-3.8.1/lib/python3.8/site-packages/meshtastic/__init__.py", line 460, in __reader
    self._handleFromRadio(self._rxBuf[HEADER_LEN:])
  File "/home/tnwhitwell/workspace/scouts/meshtastic-scouts/.direnv/python-3.8.1/lib/python3.8/site-packages/meshtastic/__init__.py", line 226, in _handleFromRadio
    self._handlePacketFromRadio(fromRadio.packet)
  File "/home/tnwhitwell/workspace/scouts/meshtastic-scouts/.direnv/python-3.8.1/lib/python3.8/site-packages/meshtastic/__init__.py", line 312, in _handlePacketFromRadio
    if asDict["decoded"]["data"]["typ"] == "CLEAR_TEXT":
KeyError: 'typ'
```

I've resolved this locally by changing
https://github.com/meshtastic/Meshtastic-python/blob/9da57e2d12ee440bd291d85f2ae64521529444ec/meshtastic/__init__.py#L310-L312

to:

```python
            if "typ" in asDict["decoded"]["data"]:
                if asDict["decoded"]["data"]["typ"] == "CLEAR_TEXT":
                    asDict["decoded"]["data"]["text"] = meshPacket.decoded.data.payload.decode(
                        "utf-8")
```

I doubt this is actually the right solution, as the datatype is being set:
https://github.com/meshtastic/Meshtastic-python/blob/9da57e2d12ee440bd291d85f2ae64521529444ec/meshtastic/__init__.py#L114

Running it through the debugger, it appears `mesh_pb2.Data.OPAQUE` is resolving to `False`, and results in it not being transmitted? maybe?

**Comment by geeksville** [comment]
thanks - I'll fixe this soon.

**Comment by geeksville** [comment]
Thanks!  Your fix is actually almost right.  You found a problem that OPAQUE is the default protobuf typ, and protobuf default values don't get populated.  I've tweaked the receiving code to add OPAQUE if no typ was specified.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/python-api-release-notes/150/11
