### ISSUE TITLE
meshtastic --qr, channel url not proper json?

### ISSUE THREAD

**Issue by nicholseric** [meshtastic/Meshtastic-python#70]
Version 1.2.10, --info reports "Channel URL https://mesh......" But --qr replies "serial interface has no attribute 'channelURL'"

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/1-2-16-alpha-of-device-android-and-python-lib-tool-is-out/2991/3
