### ISSUE TITLE
gpiowrb hangs

### ISSUE THREAD

**Issue by alport** [meshtastic/Meshtastic-python#72]
Using FW V1.2.10:

If I direct the gpiowrb command to another node fc30 whilst I am connected to 1e28 via USB ie

```
meshtastic --port /dev/cu.SLAB_USBtoUART --dest '!d1c8fc30' --gpiowrb 13 1
Connected to radio
Writing GPIO mask 0x2000 with value 0x2000 to !d1c8fc30
```

The console then hangs and the connected node 1e28 just displays a repeating progress bar until I terminate it with ^C, but the destination node fc30 indeed does set/clear its bit on GPIO13.

Any ideas?
From: [https://meshtastic.discourse.group/t/need-an-example-of-gpiowrb/1945/4?u=mike](url)

**Comment by geeksville** [comment]
fixed sometime ago but you'll need to update your device firmware and make sure to set an admin channel.
