### ISSUE TITLE
can't remove web server once it has been set on tlora-v1 firmware

### ISSUE THREAD

**Issue by vinloren** [meshtastic/Meshtastic-python#77]
I am using meshtastic python 1.1.49 and firmware 1.1.50 tlora-v1, I want to get rid of web server support in my node but if I send meshtastic --set wifi_ssid "" an error message is returned saying missing parameter needed. It appears the firmware not accepting empty strings. The host PC runs on Windows10.

See https://meshtastic.discourse.group/t/how-to-remove-web-server-support/2735

**Comment by mc-hamster** [comment]
Transferring to Meshtastic-python per Kevin's comment.

**Comment by mkinney** [comment]
@vinloren Has this issue been resolved?

**Comment by vinloren** [comment]
Actually I resolved just reflashing the device after zeroing it.
