### ISSUE TITLE
"Easy-Table" dependency has vanished from Github and PyPI

### ISSUE THREAD

**Issue by cathalgarvey** [meshtastic/Meshtastic-python#78]
As in the issue title: this dependency is no longer on PyPI, and the Github user and all the associated repos have vanished.

If anyone wants to re-upload from a local copy they can probably acquire the PyPI project name if they do so quickly.

**Comment by iz1kga** [comment]
https://pypi.org/project/easy-table/

**Comment by geeksville** [comment]
I think this is now fixed
