### ISSUE TITLE
Support to SPI LORA radios

### ISSUE THREAD

**Issue by felipeMan** [meshtastic/Meshtastic-python#84]
Hi people!
Exist any plan to made this package compatible with SPI radios. i.e Ebyte E22400M30S?
Thanks!

**Comment by geeksville** [comment]
That radio is already supported, when attached to a suitable CPU - see meshtastic-device project.  This repo is for the python tool that talks to that device.  Sorry for the late reply, for idea discussions we usually use our forum: meshtastic.discourse.group.  People there will help if you have questions on how to connect that device.
