### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-python#85]
In https://github.com/meshtastic/Meshtastic-python#changing-device-settings , the [link](https://github.com/meshtastic/Meshtastic-protobufs/blob/master/docs/docs.md#.RadioConfig.UserPreferences) to the list of preferences is dead.

**Comment by jfirwin** [comment]
This was fixed in #88

**Comment by mkinney** [comment]
Can this issue be closed?

**Comment by IZ1IVA** [comment]
> Can this issue be closed?

I forgot to close it, sorry!
