### ISSUE TITLE
Receive text API call?

### ISSUE THREAD

**Issue by sokoow** [meshtastic/Meshtastic-python#98]
Hi All,

I trawled your objects and docs seeking for non blocking or at least blocking receive call in this API - but it's missing. Any plans on adding it ?

**Comment by geeksville** [comment]
Received messages (in both text and binary) are asynchronously delivered as publishes.  So you just subscribe to meshtastic.receive.data.<portnum> or just meshtastic.receive (if you want to receive all messages).  Or if you just want text meshtastic.receive.text.  per https://github.com/meshtastic/Meshtastic-python/blob/master/meshtastic/__init__.py#L24

Example usage here:
https://github.com/meshtastic/Meshtastic-python/blob/master/meshtastic/test.py#L148

Does that help?

**Comment by geeksville** [comment]
btw @sokoow sorry for the late reply - just noticed this one...

**Comment by sokoow** [comment]
thanks @geeksville
